### ISSUE TITLE
Is it possible to run this from python terminal, and export the results to pandas or something like that?

### ISSUE THREAD

**Issue by orena1** [apockill/tdirstat#1]
Is it possible to run this from a python terminal, and export the results to pandas or something like that?

**Comment by apockill** [comment]
Hey! Thanks for your interest. Could you expand on what kind of format you'd be looking for? 

I think it definitely could be done. The logic and UI side of things are separated, so we can always add more functionality to the logic.

**Comment by orena1** [comment]
when I rethink it, I understand how it could be difficult, maybe it could be a recursive class of some kind. Never mind, thanks!

**Comment by apockill** [comment]
By the way, the whole recursive searching is actually implemented by this library. 

For example, 
```python
from tdirstat.crawler import DirectoryStat, NodeStat, get_mounts

directory_stat = DirectoryStat(
	path="/", 
	mounts_to_ignore=get_mounts(),
)

for child_directory_stat in directory_stat:
	print(child_directory_stat)

```

Each DirectoryStat can give you cumulative information about all of it's children, using the `files`, or `directories` properties. Each returns a `NodeStat` object, which tell you things like `size` and `path`.
