### ISSUE TITLE
Reinventing the Wheel

### ISSUE THREAD

**Issue by shundhammer** [apockill/tdirstat#2]
Please be aware that this already exists:

https://github.com/shundhammer/qdirstat/blob/master/doc/QDirStat-for-Servers.md
> # QDirStat for Servers
> ## Executive Summary
> QDirStat can be used for headless (no X server, no X libs) servers: It comes with a Perl script qdirstat-cache-writer that can collect data on the server. You just have to copy the data file from the server to your desktop machine where you can view the data with the normal QDirStat application.

**Comment by apockill** [comment]
I love `qdirstat` and I've enjoyed using the tool for many years. With that said, I don't think that is is quite reinventing the wheel. With your documented solution, there's:

1. No UI
2. No real-time results
3. The added hassle of having to use the tool in a specialized way, copying cache files
4. No way to delete files/directories in real-time
